SELECT
    YEAR,
    STATEFIP,
    'SPHSERVICE' AS SERVICE_TYPE,
    COUNT(SPHSERVICE) AS TOTAL_SERVICES,
    'CMPSERVICE' AS SERVICE_TYPE,
    COUNT(CMPSERVICE) AS TOTAL_SERVICES,
    COUNT(DISTINCT CASEID) AS UNIQUE_PATIENTS
FROM table
GROUP BY YEAR, STATEFIP
